// components/Project.vue
<template>
    <main @click="redirect()">
        <i class='bx bx-code-alt'></i>
        <div>
            <h1>{{ name }}</h1>
            <h2>{{ desc }}</h2>
        </div>
    </main>
</template>

<script>
export default {
    props: ["name", "desc", "url"],
    methods: {
        redirect(e) {
            location.href = this.url
        }
    },
}
</script>

<style scoped>
main {
    color: var(--white);
    background: var(--dark-two);
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    gap: 20px;
    padding: 40px;
    cursor: pointer;
    transition: .4s;
    height: 13%;
    width: 27%;
}

main:hover{
    box-shadow: var(--def-shadow);
}

i{
    font-size: 65px;
    animation-name: colorAnimation;
    animation-duration: 10s;
    animation-iteration-count: infinite;
}

h1{
    font-size: 35px;
    margin-bottom: 10px;
}

h2{
    font-size: 25px;
}

@media only screen and (max-width: 1121px) {
    main{
        width: auto;
    }
}
</style>

// src/lib/project.svelte
<script>
  import { goto } from "$app/navigation";

  export let desc
  export let url
  let audio

  function redirect() {
    audio.play()
    goto(url);
  }
</script>

<main on:click={redirect}>
  <audio bind:this={audio} preload="auto">
    <source src="/click.wav" type="audio/mpeg" />
  </audio>
  <h1 class="c"> </h1>
  <div>
    <h1><slot></slot></h1>
    <p>{desc}</p>
  </div>
</main>

<style>
main {
  display: flex;
  padding: 40px 60px 40px 60px;
  background: var(--dark-two);
  border-radius: 7px 7px 0px 0px;
  justify-content: center;
  align-content: center;
  flex-direction: row;
  cursor: pointer;
  transition: .4s;
  border: none;
  color: white;
  gap: 20px;
}

main:hover {
  box-shadow: var(--box-shadow);
}

h1 {
  font-size: 70px;
}

div h1 {
  font-size: 30px;
}

div p {
  margin-top: 10px;
  font-size: 20px; 
}
</style>
